### ISSUE TITLE
Not available in pip anymore?

### ISSUE THREAD

**Issue by cesarandreslopez** [markolofsen/py_translator#14]

**Comment by cesarandreslopez** [comment]
404 https://pypi.org/project/py-translator/

**Comment by CrollUK** [comment]
I'm having the same issue could you add it back, please. I've created a discord bot that is using your module but I'm unable atm to install to heroku :(

**Comment by vgrabovets** [comment]
This is really disappointing, can't even be installed from github.

**Comment by gustavklopp** [comment]
> This is really disappointing, can't even be installed from github.

indeed....:
`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-i6p96dnl/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-i6p96dnl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-i6p96dnl/pip-egg-info
         cwd: /tmp/pip-req-build-i6p96dnl/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-i6p96dnl/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by ghost** [comment]
Where can I install it??????*

**Comment by Brittneygogogo** [comment]
how to install?

**Comment by pcworld** [comment]
https://github.com/ssut/py-googletrans is an actively maintained replacement. It even seems to use the same API (according to #3 this library even uses or used code from googletrans?)
