### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by mjcarter95** [markolofsen/py_translator#9]
CODE:
from py_translator import Translator
translator = Translator()
trans = translator.translate('안녕하세요.')
print(trans.text)

ERROR:
Traceback (most recent call last):
  File "cleanTweet.py", line 3, in <module>
    trans = translator.translate('안녕하세요.')
  File "D:\Documents\Code\Storm\src\flask\venv\lib\site-packages\py_translator\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "D:\Documents\Code\Storm\src\flask\venv\lib\site-packages\py_translator\client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "D:\Documents\Code\Storm\src\flask\venv\lib\site-packages\py_translator\gtoken.py", line 184, in do
    self._update()
  File "D:\Documents\Code\Storm\src\flask\venv\lib\site-packages\py_translator\gtoken.py", line 56, in _update
    self.tkk = self.RE_TKK.findall(r.text)[0]
IndexError: list index out of range

Python version: 3.4.0 (VM) / 3.7.0 (Host)
Pip version: 1.5.4 (VM) / 10.0.1 (Host)
Py-translator version: 1.8.9

**Comment by mjcarter95** [comment]
This error seems to occur for the same reason that was mentioned in this thread https://github.com/markolofsen/py_translator/issues/7

I applied the fix that that the author suggested & the error no longer occurs.
